### PR TITLE
Hook support

### LINKED ISSUE #21: Siege engine issue
Referencing bug report: https://github.com/DFHack/dfhack/issues/408

### PR DESCRIPTION
**Pull request by lethosor**
Fixes #21, maybe others?
Note that this shouldn't be part of releases until you're building against the next DFHack version (after 0.43.05-r1), since it might break the three plugins you're currently distributing (probably not scripts, though).

https://github.com/DFHack/dfhack/issues/981

### CODE REVIEW

File: twbt.cpp [hunk 1]
```diff
@@ -144,7 +145,7 @@ long white_texpos, transparent_texpos;
 
 long cursor_small_texpos;
 
-static bool enabled;
+DFHACK_PLUGIN_IS_ENABLED(enabled);
```
Comment (pronvit) [inline twbt.cpp]: Will this have any side-effects since enabling/disabling isn't actually supported?

Comment (lethosor) [inline twbt.cpp]: No, it just means that `plug` will report whether TWBT is enabled (it won't actually implement `enable`/`disable` commands).
